# debian-trixie.toml
# https://packages.debian.org/search?suite=trixie&section=all&arch=any&searchon=names&keywords=search

[strategy]
method = "apt"
suite = "trixie"
mirrors = ["http://deb.debian.org/debian", "http://ftp.debian.org/debian"]

[groups.glibc]
packages = [
    "libc6",
    "libc6-dev",
    "linux-libc-dev",
]

[groups.gcc]
packages = [
    "libgcc-13-dev",
    "libgcc-s1",
]
requires = ["glibc"]

[groups.libstdcxx]
packages = [
    "libstdc++6",
    "libstdc++-13-dev",
]
requires = ["gcc"]

[groups.clang]
packages = ["libclang-rt-dev"]
requires = ["glibc"]

[groups.libcxx]
packages = [
    "libc++-dev",
    "libc++abi-dev",
]
requires = ["glibc"]

[groups.x11]
packages = [
    "x11proto-dev",
    "libx11-6",
    "libx11-dev",
    "libxext6",
    "libxext-dev",
    "libxrandr2",
    "libxrandr-dev",
    "libxcursor1",
    "libxcursor-dev",
    "libxfixes3",
    "libxfixes-dev",
    "libxi6",
    "libxi-dev",
    "libxss1",
    "libxss-dev",
    "libxtst6",
    "libxtst-dev",
    "libxkbcommon0",
    "libxkbcommon-dev",
]
requires = ["glibc"]

[groups.wayland]
packages = [
    "libwayland-client0",
    "libwayland-server0",
    "libwayland-cursor0",
    "libwayland-egl1",
    "libwayland-dev",
    "wayland-protocols",
]
requires = ["glibc"]

[groups.graphics]
packages = [
    "libdrm-dev",
    "libgbm-dev",
    "libglx-dev",
    "libglvnd-dev",
    "libegl-dev",
    "libopengl-dev",
    "libgl-dev",
    "libgles-dev",
    "libgl1",
    "libdecor-0-0",
    "libdecor-0-dev",
]
requires = ["x11", "wayland"]

[groups.audio]
packages = [
    "libsndio7.0",
    "libsndio-dev",
    "libaudio2",
    "libaudio-dev",
    "libasound2t64",
    "libasound2-dev",
    "libpulse0",
    "libpulse-dev",
    "libpipewire-0.3-0t64",
    "libpipewire-0.3-dev",
    "libjack0",
    "libjack-dev",
    "libspa-0.2-dev",
]
requires = ["glibc"]

[groups.hid]
packages = [
    "libusb-1.0-0",
    "libusb-1.0-0-dev",
    "libudev1",
    "libudev-dev",
]
requires = ["glibc"]

[groups.text]
packages = [
    "libibus-1.0-5",
    "libibus-1.0-dev",
    "libdatrie-dev",
    "libthai0",
    "libthai-dev",
    "libfribidi0",
    "libfribidi-dev",
]
requires = ["glibc"]

[groups.ffmpeg]
packages = [
    "libavcodec-dev",
    "libavformat-dev",
    "libavutil-dev",
]
requires = ["glibc"]

[groups.gio]
packages = [
    "libglib2.0-0t64",
    "libgio-2.0-dev",
    "libsysprof-capture-4-dev",
    "libpcre2-dev",
    "libffi-dev",
    "zlib1g-dev",
    "libmount-dev",
    "libblkid-dev",
    "libselinux1-dev",
    "libsepol-dev",
]
requires = ["glibc"]

[groups.other]
packages = [
    "libdbus-1-3",
    "libdbus-1-dev",
    "libsystemd0",
    "libsystemd-dev",
]
requires = ["glibc"]

[profiles.full]
groups = ["glibc", "gcc", "libstdcxx", "libcxx", "clang", "x11", "wayland", "graphics", "audio", "hid", "text", "ffmpeg", "gio", "other"]
