# CMake toolchain file for GNU/Linux SDK sysroot
# This file is bundled with the sysroot and calculates paths relative to its location

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(GLSDK_TARGET x86_64-linux-gnu)

set(CMAKE_C_COMPILER_TARGET ${GLSDK_TARGET})
set(CMAKE_CXX_COMPILER_TARGET ${GLSDK_TARGET})

get_filename_component(GLSDK_EXPECTED_PATH "${CMAKE_CURRENT_LIST_DIR}" ABSOLUTE)

set(CMAKE_SYSROOT "${GLSDK_EXPECTED_PATH}")
set(CMAKE_FIND_ROOT_PATH "${GLSDK_EXPECTED_PATH}")

set(ENV{PKG_CONFIG_SYSROOT_DIR} ${CMAKE_SYSROOT})
set(ENV{PKG_CONFIG_LIBDIR}
    "${CMAKE_SYSROOT}/usr/lib/x86_64-linux-gnu/pkgconfig"
)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_C_FLAGS_INIT "--sysroot=${CMAKE_SYSROOT}")
set(CMAKE_CXX_FLAGS_INIT "--sysroot=${CMAKE_SYSROOT}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "--sysroot=${CMAKE_SYSROOT}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "--sysroot=${CMAKE_SYSROOT}")

set(CMAKE_EXE_LINKER_FLAGS_INIT "--sysroot=${CMAKE_SYSROOT} -fuse-ld=lld")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "--sysroot=${CMAKE_SYSROOT} -fuse-ld=lld")

if(CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|amd64|aarch64|riscv64|ppc64")
    set(CMAKE_SIZEOF_VOID_P 8)
    set(GLSDK_POINTER_SIZE 64)
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "i.86|arm|armhf|armel")
    set(CMAKE_SIZEOF_VOID_P 4)
    set(GLSDK_POINTER_SIZE 32)
else()
    # Default to 64-bit
    set(CMAKE_SIZEOF_VOID_P 8)
    set(GLSDK_POINTER_SIZE 64)
endif()

set(HAVE_PTRDIFF_T 1)
set(NEED_PTRDIFF_T 0)
